# Generated by Django 4.2.19 on 2025-09-25 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_alter_notification_from_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='Hash of user settings and preferences', max_length=64, unique=True)),
                ('recommendations_data', models.JSONField(help_text='Cached AI recommendations data')),
                ('page', models.PositiveIntegerField(help_text='Page number for pagination')),
                ('per_page', models.PositiveIntegerField(help_text='Items per page')),
                ('total_matches', models.PositiveIntegerField(help_text='Total number of matches found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this cache entry expires')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this cache entry is still valid')),
                ('settings_hash', models.CharField(help_text='Hash of user settings when cache was created', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'cache_key'], name='social_aire_user_id_d827d1_idx'), models.Index(fields=['expires_at'], name='social_aire_expires_e4b5a9_idx'), models.Index(fields=['is_valid'], name='social_aire_is_vali_96cbd0_idx')],
            },
        ),
    ]
