# Generated by Django 4.2.19 on 2025-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_notification_notification_type_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('share', 'Share'), ('follow', 'Follow'), ('message', 'Message'), ('match', 'Match')], max_length=10),
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
