# Generated by Django 5.2.5 on 2025-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='matches_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_online_status',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
